config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :create, :new, :show]
  end
  # Defines the root path route ("/")
  # root "articles#index"
  resources :posts, only: %i[new create update destroy] do
    resources :comments
      resources :likes
  end   
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.is? :admin
      can :manage, :all
    else
      can :manage, Post, users_id: user.id
      can :manage, Comment, users_id: user.id
      can :read, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'users_id'
  belongs_to :post

  after_create :update_comments_counter
  after_destroy :update_comments_counter_after_destroy

  private

  def update_comments_counter
    post.increment!(:Comments_Counter)
  end

  def update_comments_counter_after_destroy
    post.decrement!(:Comments_Counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'users_id'
  belongs_to :post

  after_create :update_likes_counter

  private

  def update_likes_counter
    post.increment!(:Likes_Counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'users_id'
  has_many :likes
  has_many :comments
  validates :Title, presence: true, length: { maximum: 250 }
  validates :Likes_Counter, :Comments_Counter, numericality: { greater_than_or_equal_to: 0 }

  after_create :update_posts_counter
  after_destroy :update_posts_counter_after_destroy

  def recent_comments
    comments.order('created_at Desc').includes(:author).limit(5)
  end

  private

  def update_posts_counter
    author.increment!(:Posts_Counter)
  end

  def update_posts_counter_after_destroy
    author.decrement!(:Posts_Counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'users_id'
  has_many :comments, foreign_key: 'users_id'
  has_many :likes, foreign_key: 'users_id'
  validates :Name, presence: true
  validates :Posts_Counter, numericality: { greater_than_or_equal_to: 0 }
  validates :password, presence: true, length: { minimum: 6 }
  validates :email, presence: true, length: { maximum: 255 }, uniqueness: { case_sensitive: true }

  ROLES = %i[admin default].freeze

  def is?(requested_role)
    role == requested_role.to_s
  end

  def recent_posts
    posts.order('created_at DESC').limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:Name, :Photo, :Bio, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:email, :password, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :current_user, only: [:create]

  def create
    @comment = current_user.comments.new(comments_params)
    @comment.users_id = current_user.id
    @comment.post_id = params[:post_id]

    if @comment.save
      flash[:success] = 'Comment saved successfully'
      redirect_to user_post_path(current_user.id, Post.find(params[:post_id]))
    else
      render :new
      flash.now[:error] = 'Comment not saved'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    flash[:success] = 'Comment deleted successfully'
    redirect_to user_post_path(current_user.id, Post.find(@comment.post_id))
  end

  def comments_params
    params.require(:comment).permit(:Text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :current_user, only: [:create]

  def create
    @post = Post.find(params[:post_id])
    new_like = current_user.likes.new(
      users_id: current_user.id,
      post_id: @post.id
    )

    if new_like.save
      flash[:success] = 'Like saved successfully'
      redirect_to user_post_path(current_user.id, @post)
    else
      render :new
      flash.now[:error] = 'Like not saved'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  before_action :current_user, only: [:create]

  def index
    @user = User.find(params[:user_id])
    # avoid N+1 query
    @posts = @user.posts
  end

  def show
    @post = Post.find(params[:id])
    @user = User.find(@post.users_id)
    @comments = @post.comments
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    @post.users_id = current_user.id

    if @post.save
      flash[:success] = 'Post saved successfully'
      redirect_to user_path(current_user.id)
    else
      render :new
      flash.now[:error] = 'Post not saved'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:success] = 'Post deleted successfully'
    redirect_to "/users/#{params[:id]}"
  end

  private

  def post_params
    params.require(:post).permit(:Title, :Text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

   <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= yield %>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/posts/_add_comments.html.erb
<%= form_with url: "/posts/#{@post.id}/comments", scope: :comment do |form| %>
  <div class="container" style="padding: 2rem; marging-top: 2rem;">
    <div class="mb-3">
      <%= form.text_area :Text, placeholder: "Add your comment...", class:"form-control", rows: 5, required: true %>
    </div>
    <div>
      <%= form.submit "Add comment", class:'btn btn-outline-info' %>
    </div>
  </div>
<% end %>

app/views/posts/index.html.erb
<div class='container'>
    <div class="card mb-3 border-info mb-3 " style="max-width: 900px;">
      <div class="row g-0">
        <div class="col-md-4">
          <img src="<%=@user.Photo%>" class="img-fluid rounded-start" alt="profile photo">
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title">
              <h1><%= @user.Name %></h1>
            </h5>
            <p class="card-text"><%=  @user.Bio  %></p>
            <p class="card-text text-end"><small class="text-muted">Number of posts: <%=  @user.Posts_Counter  %></small></p>
          </div>
        </div>
      </div>
    </div>
    <div class='u-detail-rec-posts'>
        <% @posts.each  do |post| %>
            <div class="card border-info mb-3" style="max-width: 900px;">
              <div class="card-header bg-info">Post: <%= link_to "#{post.Title}", user_post_path(@user.id, post.id), class: 'post-link' %></div>
              <div class="container">
                <div class="card-body text-dark">
                  <p class="card-text"><%= post.Text %></p>
                  <p class="card-text text-end">
                    <small class="text-muted">
                      <% if post.Comments_Counter != 0 %>
                        Likes: <%= post.Likes_Counter %>
                      <% else %>
                        Comments: <%= post.Comments_Counter %> Likes: <%= post.Likes_Counter %>
                      <% end %>
                    </small>
                  </p>
                  <% if can? :destroy, post %>
                    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                      <%= button_to "Delete Post", post, method: :delete , class: "btn btn-outline-danger"%>
                    </div>
                  <% end %>
                </div>
              </div>
              
              <% if post.Comments_Counter != 0 %>
                <div class="card border-info mb-3" style="width: 840px; margin: 0 auto; margin-bottom: 2rem;">
                  <div class="card-header bg-info">
                    Comments: <%= post.Comments_Counter %>
                  </div>
                  <ul class="list-group list-group-flush">
                    <% post.recent_comments.each do |comment| %>
                        <% if post.id === comment.post_id %>
                          <li class="list-group-item ">
                            <%= comment.author.Name %>: <%= comment.Text  %>
                          </li>
                        <% end %>
                    <% end %>
                  </ul>
                </div>
              <% else %>
                <br>
              <% end %>
            </div>            
        <% end %>

        <button class="btn btn-outline-info">
          Pagination
        </button>
    </div>
</div>

app/views/posts/new.html.erb
<h1 class='hello_error'><%= flash[:error] %></h1>

<%= form_with model: @post do |f| %>
  <div class="card container" style="padding: 3rem;">
    <div class='mb-3'>
      <%= f.label :title, class:"form-label" %>
      <%= f.text_field :Title, class:"form-control" %>
    </div>
    <div class='mb-3'>
      <%= f.label :text, class:"form-label" %>
      <%= f.text_area :Text, class:"form-control" %>
    </div>
    <div>
      <%= f.submit "Add new post", class:'btn btn-outline-info' %>
    </div>
  </div>
<% end %>

app/views/posts/show.html.erb
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
  </symbol>
  <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
  </symbol>
  <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
  </symbol>
</svg>
<div class="container" style="margin: 2rem auto;">
  <div class="card border-info mb-3" style="max-width: 900px;">
    <div class="card-header bg-info"><%= @post.Title %> by <%= @post.author.Name %></div>
    <div class="container">
    <div class="card-body text-dark">
        <h5 class="card-title"><%= @post.Title %></h5>
        <p class="card-text"><%= @post.Text %></p>
        <p class="card-text text-end"><small class="text-muted"> Likes: <%= @post.Likes_Counter %> </small></p>
        <% flash.each do |type, msg| %>
          <div class="alert alert-success d-flex align-items-center" role="alert">
            <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg>
            <div>
                <%= msg %>
            </div>
          </div>
        <% end %>
        <%= form_with url: "/posts/#{@post.id}/likes", scope: :like do |form| %>
            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                <%= form.submit "Like ", class: "btn btn-outline-danger"%>
            </div>
        <% end %>
    </div>
    </div>
  
    <div class="card border-info mb-3" style="width: 840px; margin: 0 auto; margin-bottom: 2rem;">
        <div class="card-header bg-info">
            Comments: <%= @post.Comments_Counter %>
        </div>
        <ul class="list-group list-group-flush">
            <% @comments.includes(:author).each do |comment| %>
                <li class="list-group-item d-flex bd-highlight">
                  <div class="p-2 w-100 bd-highlight">
                    <%= comment.author.Name %>: <%= comment.Text  %>
                  </div>
                  <% if can? :destroy, comment %>
                    <div class="p-2 flex-shrink-1 bd-highlight">
                      <%= button_to "Delete", post_comment_path(@post, comment), method: :delete, class: "btn btn-outline-danger" %>
                    </div>
                  <% end %>
                </li>
            <% end %>
        </ul>
    </div>
    <%= render partial: "add_comments", local: { post: @post } %>
  </div>
</div>

app/views/users/index.html.erb
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
  </symbol>
  <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
  </symbol>
  <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
  </symbol>
</svg>
<% flash.each do |type, msg| %>
  <div class="alert alert-success d-flex align-items-center" style="max-width: 900px; margin: 1rem auto;" role="alert">
    <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg>
    <div>
        <%= notice %>
        <%= msg %>
        <%= alert %>
    </div>
  </div>
<% end %>

<% if user_signed_in? %>
  <div style="max-width: 900px; margin: 1rem auto;">
    <%= button_to  "Sign Out", destroy_user_session_path, method: :delete, class:"btn btn-outline-info" %>
  </div>
<% else %>
  <div style="max-width: 900px; margin: 1rem auto;">
    <%= link_to  "Sign In", new_user_session_path, class:"btn btn-outline-info" %>
  </div>
<% end %>

<% @users.each do |user| %>
  <% if current_user === user %>
    <div class="container">
      <div class="card mb-3 border-danger mb-3" style="max-width: 900px; margin: 0 auto;">
        <div class="row g-0">
          <div class="col-md-4">
            <img src="<%=user.Photo%>" style="width: 100% \9;" class="img-fluid rounded-start" alt="profile photo">
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title">
                <%= link_to user_path(user.id), class:"link-info" do %>
                  <h1><%= user.Name %></h1>
                <% end %>
              </h5>
              <p class="card-text"><%=  user.Bio  %></p>
              <p class="card-text text-end"><small class="text-muted">Number of posts: <%=  user.Posts_Counter  %></small></p>
            </div>
          </div>
        </div>
      </div> 
    </div>
  <% else %>
    <div class="container">
      <div class="card mb-3 border-info mb-3" style="max-width: 900px; margin: 0 auto;">
        <div class="row g-0">
          <div class="col-md-4">
            <img src="<%=user.Photo%>" style="width: 100% \9;" class="img-fluid rounded-start" alt="profile photo">
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title">
                <%= link_to user_path(user.id), class:"link-info" do %>
                  <h1><%= user.Name %></h1>
                <% end %>
              </h5>
              <p class="card-text"><%=  user.Bio  %></p>
              <p class="card-text text-end"><small class="text-muted">Number of posts: <%=  user.Posts_Counter  %></small></p>
            </div>
          </div>
        </div>
      </div> 
    </div>
  <% end %>
<%end%>

app/views/users/show.html.erb
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
  </symbol>
  <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
  </symbol>
  <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
  </symbol>
</svg>
<div class="container">
    <div class="card mb-3 border-info mb-3" style="max-width: 900px">
      <div class="row g-0">
        <div class="col-md-4">
          <img src="<%=@user.Photo%>" class="img-fluid rounded-start" alt="profile photo">
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title">
              <h1><%= @user.Name %></h1>
            </h5>
            <p class="card-text"><%=  @user.Bio  %></p>
            <p class="card-text text-end"><small class="text-muted">Number of posts: <%=  @user.Posts_Counter  %></small></p>
          </div>
        </div>
      </div>
    </div> 
     <% flash.each do |type, msg| %>
      <div class="alert alert-success d-flex align-items-center" style="max-width: 900px;" role="alert">
        <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg>
        <div>
            <%= msg %>
        </div>
      </div>
    <% end %>
    <div style="margin-bottom: 2rem;">
      <% @user.recent_posts.each  do |post| %>
        <% if @user.id === post.users_id %>
          <div class="c">
            <div class="card border-info mb-3" style="max-width: 900px;">
              <div class="card-header bg-info">Post: <%= link_to "#{post.Title}", user_post_path(@user.id, post.id), class:"link-dark" %></div>
              <div class="card-body text-dark">
                <p class="card-text"><%= post.Text %></p>
                <p class="card-text text-end">
                  <small class="text-muted"> 
                    Comments: <%= post.Comments_Counter %> Likes: <%= post.Likes_Counter %> 
                  </small>
                </p>
                <% if can? :destroy, post %>
                  <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                    <%= button_to "Delete Post", post, method: :delete , class: "btn btn-outline-danger"%>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
      <br>
      <% if user_signed_in? == true && @user.id == current_user.id %>
        <button class='btn btn-outline-info'>
          <%= link_to 'Add new post', new_user_post_path(@user.id), class: "nav-link" %>
        </button>
      <% end %>
      <button class="btn btn-outline-info">
        <%= link_to 'See all Posts', user_posts_path(@user), class:"nav-link"%>
      </button>
    </div>
</div>